### ISSUE TITLE
Docker - Supabase 

### ISSUE THREAD

**Issue by Vincent-devSG** [adaltas/ece-webtech-2022-fall#12]
## Description

Following the steps you gave, then the official documentation: https://supabase.com/docs/guides/resources/self-hosting/docker.
After modifying the values of POSTGRES_PASSWORD, JWT_SECRET etc, docker compose up, fails permanently. 
It fails saying the password authentification failed for user supabase_admin :  FATAL 28P01 (invalid_password) password authentication failed for user "supabase_admin"
Also: FATAL:  password authentication failed for user \"authenticator\"\n","hint":null,"message":"Database connection error.

## Screenshots

If applicable, add screenshots to help explain your problem:
![image](https://user-images.githubusercontent.com/78809113/208069843-9a850851-e12b-4e0a-80fc-42a72b8edbf7.png)

## Environment:

Docker Desktop 4.15.0

**Comment by sergkudinov** [comment]
Does it work if you don’t modify these values? If yes, you must carefully check what you brake when doing it.

**Comment by sergkudinov** [comment]
Hi @Vincent-devSG 
If you have fixed the issue, please, close it describing your workaround.

**Comment by sergkudinov** [comment]
Closing myself
