### ISSUE TITLE
POST Article Route

### ISSUE THREAD

**Issue by Eagles27** [adaltas/ece-webtech-2022-fall#4]
## Description

**Should we write in the JSON file the new user ?** 
Because I think it's harder to do than implementing a Database

**Comment by sergkudinov** [comment]
There are no instructions to write users to the files. If you want to implement user's functionality, you can work with in memory JavaScript variables like [this](https://github.com/adaltas/ece-webtech-2022-fall/blob/main/courses/webtech/modules/03.webapi/lab.md#1-prepare-an-example-database-model).

Don't implement any DB, we will do it later.

**Comment by sergkudinov** [comment]
@Eagles27 
Please, close this issue if you got an answer.
