### ISSUE TITLE
Lab 4: start the app

### ISSUE THREAD

**Issue by Arthurhrd** [adaltas/ece-webtech-2022-fall#6]
## Description

After I the run `npx create-next-app@latest`. It create the app folder.
And when I try to run the app. I have an issue.

## Screenshots
![Screenshot from 2022-10-13 17-00-22](https://user-images.githubusercontent.com/78748626/195633634-240bfa7a-38cc-47cb-b2fd-4fbd6e47af48.png)

## Environment:

    OS: [Ubuntu]

**Comment by wdavidw** [comment]
HI @Arthurhrd, when submitting an issue, screenshot are not welcome. Instead you should provide a reproductible environment, copy/pasting your setup and the error in the output. People who assist you, sometime on their free time when working with open source project, don't waste time and can for example google your error message. Here is an example:

```bash
yarn create next-app
cd next-app
yarn run dev
# Output is
...copy/paste of the output...
```
