### ISSUE TITLE
Salles Mercredi 9

### ISSUE THREAD

**Issue by PaulFarault** [adaltas/ece-webtech-2022-fall#7]
Bonjours à tous, des personnes ont-elles accès aux numéro des salles d'aujourd'hui s'il vous plaît ?

Cela nous aiderait avec le soucie d'hyperplanning

A tout de suite

**Comment by Kowken** [comment]
Bonjour

Nous avons rendez-vous en EM317 (E1) à 10h45.

Cordialement
________________________________
De : Paul Farault ***@***.***>
Envoyé : mercredi, novembre 9, 2022 8:40 AM
À : adaltas/ece-webtech-2022-fall ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [adaltas/ece-webtech-2022-fall] Salles Mercredi 9 (Issue #7)


Bonjours à tous, des personnes ont-elles accès aux numéro des salles d'aujourd'hui s'il vous plaît ?

Cela nous aiderait avec le soucie d'hyperplanning

A tout de suite
