### ISSUE TITLE
Can't use make in window version

### ISSUE THREAD

**Issue by patrawi** [adaltas/ece-webtech-2022-fall#8]
## Description

In lab09, in order to make a OAuth connect, you have to run make for looking up in Makefile. However, it gives an error which i try to fix it. Unfortunately, I fail. Could you please help me 

## To Reproduce
Using window and run make after cloning it

# Install
git clone https://github.com/dexidp/dex.git
cd dex
make build![image](https://user-images.githubusercontent.com/67262217/204765609-19aba7b6-0d84-4629-ac08-557fa61c57f9.png)
# Start
./bin/dex serve examples/config-dev.yaml

## Expected behavior
expect it work 

## Screenshots
![image](https://user-images.githubusercontent.com/67262217/204765609-19aba7b6-0d84-4629-ac08-557fa61c57f9.png)

## Environment:

    OS: Window 11

**Comment by wdavidw** [comment]
The joy is programming on Windows, try with an Ubuntu vm and let us now.
